// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB6L2Nz44moeHh2XH3jEV6Skw4xgceuCi0',
    appId: '1:551601080933:web:08a0405e0f06fa7d59d48c',
    messagingSenderId: '551601080933',
    projectId: 'suasaudeapp-56441',
    authDomain: 'suasaudeapp-56441.firebaseapp.com',
    storageBucket: 'suasaudeapp-56441.appspot.com',
    measurementId: 'G-PZZSXBFTRH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBKFppnJ74V2cYF03fmlAWtcG2PlHVBdWM',
    appId: '1:551601080933:android:7e3c73cafe39334059d48c',
    messagingSenderId: '551601080933',
    projectId: 'suasaudeapp-56441',
    storageBucket: 'suasaudeapp-56441.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDS-yoIa-ivhffBiQRAAw-Zg_H0yAr1XOc',
    appId: '1:551601080933:ios:19152b76a118373959d48c',
    messagingSenderId: '551601080933',
    projectId: 'suasaudeapp-56441',
    storageBucket: 'suasaudeapp-56441.appspot.com',
    iosClientId: '551601080933-djlvodr2va5kfhi78khjemumq4fd7hcv.apps.googleusercontent.com',
    iosBundleId: 'com.example.suaSaudeApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDS-yoIa-ivhffBiQRAAw-Zg_H0yAr1XOc',
    appId: '1:551601080933:ios:19152b76a118373959d48c',
    messagingSenderId: '551601080933',
    projectId: 'suasaudeapp-56441',
    storageBucket: 'suasaudeapp-56441.appspot.com',
    iosClientId: '551601080933-djlvodr2va5kfhi78khjemumq4fd7hcv.apps.googleusercontent.com',
    iosBundleId: 'com.example.suaSaudeApp',
  );
}
